build:
    environment:
        php: '5.6.9'

    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=some-file --whitelist src'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
                    
filter:
    excluded_paths: [tests/*]
